# Generated by Django 3.0.7 on 2020-07-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200701_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bonus_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='visits',
            field=models.IntegerField(default=0),
        ),
    ]
