# Generated by Django 3.0.7 on 2020-07-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200701_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bonus_spent',
            field=models.IntegerField(default=0),
        ),
    ]
