# Generated by Django 3.0.7 on 2020-07-04 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_bonus_spent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bonus_spent',
        ),
    ]
