# Generated by Django 3.0.8 on 2020-07-21 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField(max_length=255, null=True)),
                ('time', models.CharField(choices=[('1', '11:00 - 13:00'), ('2', '13:00 - 15:00'), ('3', '15:00 - 17:00'), ('4', '17:00 - 19:00')], max_length=255)),
                ('address', models.CharField(choices=[('m', 'Мякинино'), ('c', 'Чеховская')], max_length=255)),
                ('work', models.CharField(choices=[('1', 'Ламинирование'), ('2', 'Ламинирование + коррекция'), ('3', 'Ламинирование + окрашивание'), ('4', 'Ламинирование + коррекция + окрашивание'), ('5', 'Протеиновое восстановление'), ('6', 'Коррекция бровей пинцетом'), ('7', 'Окрашивание бровей'), ('8', 'Архитектура + окрашивание'), ('9', 'Эпиляция над губой'), ('10', 'Осветление'), ('11', 'Осветление + коррекция')], max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('comment', models.TextField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('p', 'Process'), ('d', 'Done')], default='p', max_length=255)),
                ('price', models.IntegerField(default=0, null=True)),
                ('booking_bonus', models.IntegerField(default=0)),
                ('bonus_spent', models.IntegerField(default=0)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='accounts.Profile')),
            ],
        ),
    ]
