# Generated by Django 3.0.7 on 2020-06-23 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('work', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('comment', models.TextField(max_length=500)),
            ],
        ),
    ]
