# Generated by Django 3.0.7 on 2020-06-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='address',
            field=models.CharField(choices=[('m', 'Мякинино'), ('c', 'Чеховская')], max_length=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='comment',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.CharField(choices=[('1', '11:00 - 13:00'), ('2', '13:00 - 15:00'), ('3', '15:00 - 17:00'), ('4', '17:00 - 19:00')], max_length=15),
        ),
    ]
