# Generated by Django 3.0.7 on 2020-06-24 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20200624_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='name',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.CharField(choices=[('1', '11:00 - 13:00'), ('2', '13:00 - 15:00'), ('3', '15:00 - 17:00'), ('4', '17:00 - 19:00')], max_length=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='work',
            field=models.CharField(max_length=55),
        ),
    ]
