# Generated by Django 3.0.7 on 2020-06-30 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20200624_1642'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserExtends',
        ),
    ]
