# Generated by Django 3.0.7 on 2020-07-01 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0006_delete_userextends'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.CharField(choices=[('1', '11:00 - 13:00'), ('2', '13:00 - 15:00'), ('3', '15:00 - 17:00'), ('4', '17:00 - 19:00')], max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='work',
            field=models.CharField(choices=[('1', 'Ламинирование'), ('2', 'Ламинирование + коррекция'), ('3', 'Ламинирование + окрашивание'), ('4', 'Ламинирование + коррекция + окрашивание'), ('5', 'Протеиновое восстановление'), ('6', 'Коррекция бровей пинцетом'), ('7', 'Окрашивание бровей'), ('8', 'Архитектура + окрашивание'), ('9', 'Эпиляция над губой'), ('10', 'Осветление'), ('11', 'Осветление + коррекция')], max_length=55),
        ),
    ]
