# Generated by Django 3.0.7 on 2020-07-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20200701_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
