# Generated by Django 3.0.7 on 2020-07-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_auto_20200704_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='bonus_spent',
            field=models.IntegerField(default=0),
        ),
    ]
