# Generated by Django 3.0.7 on 2020-07-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_booking_bonus_spent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='work',
            field=models.CharField(choices=[('Ламинирование', 'First'), ('Ламинирование + коррекция', 'Second'), ('Ламинирование + окрашивание', 'Third'), ('Ламинирование + коррекция + окрашивание', 'Fourth'), ('Протеиновое восстановление', 'Fifth'), ('Коррекция бровей пинцетом', 'Sixth'), ('Окрашивание бровей', 'Seventh'), ('Архитектура + окрашивание', 'Eighth'), ('Эпиляция над губой', 'Nineth'), ('Осветление', 'Tenth'), ('Осветление + коррекция', 'Eleventh')], max_length=55),
        ),
    ]
