# Generated by Django 3.0.7 on 2020-07-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_auto_20200705_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='work',
            field=models.CharField(choices=[('1', 'Ламинирование'), ('2', 'Ламинирование + коррекция'), ('3', 'Ламинирование + окрашивание'), ('4', 'Ламинирование + коррекция + окрашивание'), ('5', 'Протеиновое восстановление'), ('6', 'Коррекция бровей пинцетом'), ('7', 'Окрашивание бровей'), ('8', 'Архитектура + окрашивание'), ('9', 'Эпиляция над губой'), ('10', 'Осветление'), ('11', 'Осветление + коррекция')], max_length=55),
        ),
    ]
