# Generated by Django 3.0.7 on 2020-07-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_auto_20200707_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
