# Generated by Django 3.0.7 on 2020-07-14 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_booking_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='datetime',
        ),
    ]
