# Generated by Django 3.0.7 on 2020-07-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_remove_booking_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(max_length=100),
        ),
    ]
