# Generated by Django 3.0.7 on 2020-07-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_auto_20200720_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='address',
            field=models.CharField(choices=[('m', 'Мякинино'), ('c', 'Чеховская')], max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='bonus_spent',
            field=models.IntegerField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_bonus',
            field=models.IntegerField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='comment',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='price',
            field=models.IntegerField(default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('p', 'Process'), ('d', 'Done')], default='p', max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.CharField(choices=[('1', '11:00 - 13:00'), ('2', '13:00 - 15:00'), ('3', '15:00 - 17:00'), ('4', '17:00 - 19:00')], max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='work',
            field=models.CharField(choices=[('1', 'Ламинирование'), ('2', 'Ламинирование + коррекция'), ('3', 'Ламинирование + окрашивание'), ('4', 'Ламинирование + коррекция + окрашивание'), ('5', 'Протеиновое восстановление'), ('6', 'Коррекция бровей пинцетом'), ('7', 'Окрашивание бровей'), ('8', 'Архитектура + окрашивание'), ('9', 'Эпиляция над губой'), ('10', 'Осветление'), ('11', 'Осветление + коррекция')], max_length=255),
        ),
    ]
