# Generated by Django 3.0.7 on 2020-07-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_auto_20200720_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='bonus_spent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='price',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
